question_data = [{"question":"The full form of CSS is Cascading Style Sheet ?","correct_answer":"True","incorrect_answers":["True"]},
{"question":"The programming language Python is based off a modified version of JavaScript;.","correct_answer":"False","incorrect_answers":["True"]},
{"question":"Pointers were not used in the original C programming language; they were added later on in C++.","correct_answer":"False","incorrect_answers":["True"]},
{"question":"Windows NT is a monolithic kernel.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ","correct_answer":"True","incorrect_answers":["False"]},
{"question":"RAM stands for Random Access Memory.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Ada Lovelace is often considered the first computer programmer.","correct_answer":"True","incorrect_answers":["False"]},
{"question":"MacOS is based on Linux.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Science: Computers","type":"boolean","difficulty":"medium","question":"The open source program Redis is a relational database server.","correct_answer":"False","incorrect_answers":["True"]},
{"question":"AMD created the first consumer 64-bit processor.","correct_answer":"True","incorrect_answers":["False"]},
{"question":"HTML stands for Hypertext Markup Language.","correct_answer":"True","incorrect_answers":["False"]},
{"question":"The Windows 7 operating system has six main editions.","correct_answer":"True","incorrect_answers":["False"]},
{"question":"The Windows ME operating system was released in the year 2000.","correct_answer":"True","incorrect_answers":["False"]},
{"question":"The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.","correct_answer":"False","incorrect_answers":["True"]},
{"question":"The last Windows operating system to be based on the Windows 9x kernel was Windows 98.","correct_answer":"False","incorrect_answers":["True"]},
{"question":"Linux was first created as an alternative to Windows XP.","correct_answer":"False","incorrect_answers":["True"]},
{"question":"Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.","correct_answer":"False","incorrect_answers":["True"]},
{"question":"A Boolean value of 0 represents which of these words?","correct_answer":"False","incorrect_answers":["True"]},
{"question":"The Python programming language gets its name from the British comedy group Monty Python.","correct_answer":"True","incorrect_answers":["False"]},
{"question":"The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.","correct_answer":"True","incorrect_answers":["False"]}]